### ISSUE TITLE
Do we have a plan to support doom-one light theme?

### ISSUE THREAD

**Issue by BarretRen** [NTBBloodbath/doom-one-vscode#3]
I like doom-one themes very much and I also use the light/dark themes on nvim.
But it only support the dark theme for vscode, do we have a plan to support doom-one light theme for vscode?
If so, that will be so cool.

**Comment by NTBBloodbath** [comment]
I really don't know how to implement it in VSCode and I'm not using the editor that frequently anymore. However, if anyone wants to add it I'd be happy to accept their PR

**Comment by BarretRen** [comment]
> I really don't know how to implement it in VSCode and I'm not using the editor that frequently anymore. However, if anyone wants to add it I'd be happy to accept their PR

OK, thanks. Maybe I can porting the light theme from nvim, I will try it.
